# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
resources:
- repo: self
queue:
  name: Hosted VS2017
steps:

- powershell: |
    .\build.ps1 -InstallDependencies:$true -verbose -tasks 'nothing'
  displayName: 'PowerShell - Install Dependencies'

- powershell: |
    .\build.ps1 -verbose -tasks 'build'
  displayName: 'PowerShell - Build'

- powershell: |
    .\build.ps1 -verbose -tasks 'test'
  displayName: 'PowerShell - Test'
  env:
    mvpapikey: $(mvpapikey)

- powershell: |
    .\build.ps1 -verbose -tasks 'deploy'
  displayName: 'PowerShell - Deploy'
  env:
    psgallerykey: $(psgallerykey)

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit